PROSPECT_POOL = []
FRANCHISES = []
teamnames = [
    "Red Wings",
    "Ducks",
    "Coyotes",
    "Bruins",
    "Sabres",
    "Flames",
    "Hurricanes",
    "Blackhawks",
    "Avalanche",
    "Blue Js",
    "Stars",
    "Oilers",
    "Panthers",
    "Kings",
    "Wild",
    "Canadiens",
    "Predators",
    "Devils",
    "Islanders",
    "Rangers",
    "Senators",
    "Flyers",
    "Penguins",
    "Sharks",
    "Kraken",
    "Blues",
    "Lightning",
    "Maple Leafs",
    "Canucks",
    "G Knights",
    "Capitals",
    "Jets",
]

AHLteamnames = [
    "Griffins",
    "Gulls",
    "Roadrunners",
    "Bruins AHL",
    "Americans",
    "Wranglers",
    "Wolves AHL",
    "IceHogs",
    "Eagles",
    "Monsters",
    "Stars AHL",
    "Condors",
    "Checkers",
    "Reign",
    "Wild AHL",
    "Rocket",
    "Admirals",
    "Comets AHL",
    "Islanders AHL",
    "Wolf Pack",
    "Senators AHL",
    "Phantoms",
    "Penguins AHL",
    "Barracuda",
    "Firebirds",
    "Thunderbird",
    "Crunch",
    "Marlies",
    "Canucks AHL",
    "Knights",
    "Bears",
    "Moose",
]

EUteamnames = [
    "Frölunda",
    "Färjestad",
    "Skellefteå",
    "Luleå",
    "Örebro",
    "HV71",
    "Linköping",
    "Växjö",
    "Djurgården",
    "Brynäs",
    "Timrå",
    "Rögle",
    "Malmö",
    "Sparta",
    "Slovan",
    "Zagreb",
    "Bern",
    "Zürich",
    "Geneva",
    "Lausanne",
    "Eisbären",
    "Adler",
    "Red Bull",
    "Kölner",
    "Düsseldorf",
    "Ingolstadt",
    "Capitals EU",
    "Lions",
    "Wolves EU",
    "IFK",
    "Ilves",
    "Nordics",
]

CHLteamnames = [
    "Titans",
    "Voyagers",
    "Whales",
    "Stampede",
    "Elks",
    "Lynx",
    "Blizzard",
    "Nordiques",
    "Mariners",
    "Steel",
    "Knights CHL",
    "Pioneers",
    "Cougars",
    "Royals",
    "Falcons",
    "Raiders CHL",
    "Wheat Kings",
    "Rangers CHL",
    "Spitfires",
    "Colts",
    "Generals",
    "Petes",
    "Wolves CHL",
    "Sting",
    "Icehawks",
    "Sea Dogs",
    "Wildcats",
    "Islanders CHL",
    "Foxes",
    "Timberwolve",
    "Hurricane",
    "Tigers",
]

SPHLteamnames = [
    "Steelhawks",
    "River Rats",
    "Warhawks",
    "Blaze",
    "Vipers SPHL",
    "Bruisers SPHL",
    "Outlaws SPHL",
    "Bandits SPHL",
    "Rebels",
    "Barracudas",
    "Fury",
    "Grizzlies SPHL",
    "Wraiths",
    "Cyclones SPHL",
    "Thunderbolt",
    "Rattlers",
    "Kodiaks",
    "Icebreakers",
    "Smoke",
    "Savages",
    "Renegades SPHL",
    "Mavericks SPHL",
    "Gladiators",
    "Predators SPHL",
    "Wolves SPHL",
    "Arsenal",
    "Phantoms SPHL",
    "Raiders SPHL",
    "Sentinels",
    "Bulls",
    "Havoc",
    "Crusaders",
]

FHLteamnames = [
    "Crushers",
    "Bandits FHL",
    "Frostbite",
    "Coyotes FHL",
    "Lumberjacks",
    "Reapers",
    "Thunder",
    "Mavericks FHL",
    "Sharks FHL",
    "Vipers FHL",
    "Howlers",
    "Raptors",
    "Outlaws FHL",
    "Breakers",
    "Guardians",
    "Maulers",
    "Cyclones FHL",
    "Sabres FHL",
    "Bruisers FHL",
    "Grizzlies FHL",
    "Invaders",
    "Hammers",
    "Renegades FHL",
    "Wolfpack",
    "Smashers",
    "Phantoms FHL",
    "bombers",
    "Nomads",
    "Brawlers",
    "Stallions",
    "Comets FHL",
    "Barricade",
]

REC1teamnames = [
    "Beers",
    "Bruised",
    "Slapshots",
    "Pylons",
    "Shinpadless",
    "Chuggers",
    "Danglers",
    "Benders",
    "Muffins",
    "Goons",
    "Snipers",
    "Benchmen",
    "Pucks",
    "Soggy",
    "Tenders",
    "Mallets",
    "Stumblers",
    "Wobblers",
    "Lagers",
    "Stickmen",
    "Floppers",
    "Zambonis",
    "Noes",
    "Brickhands",
    "Sauce",
    "Clappers",
    "Cellys",
    "Keggers",
    "Dusters",
    "Scrubs",
    "Pantsless",
    "Oils",
]

REC2teamnames = [
    "Beerpong",
    "Hangovers",
    "Sloshers",
    "Mishaps",
    "Whiffers",
    "Turnovers",
    "Triples",
    "Puckheads",
    "Glizzies",
    "Toasteds",
    "Frosties",
    "Chillers",
    "Lads",
    "Benchers",
    "Puddles",
    "Shafted",
    "Brickies",
    "Scrappers",
    "Drifters",
    "Milds",
    "Suds",
    "Fumbles",
    "Clutchless",
    "Drunks",
    "Coasters",
    "Bloopers",
    "Skaters",
    "Shufflers",
    "Flails",
    "Noodles",
    "Rinkrats",
    "Lastcall",
]

FNAME = [
    "Alex",
    "Andrew",
    "Anthony",
    "Aaron",
    "Adam",
    "Adrian",
    "Aiden",
    "Alan",
    "Albert",
    "Alec",
    "Aleksandr",
    "Alexei",
    "Alfie",
    "Anders",
    "Andre",
    "Andreas",
    "Andy",
    "Anton",
    "Artyom",
    "Blake",
    "Brandon",
    "Brian",
    "Brent",
    "Brock",
    "Brady",
    "Brett",
    "Ben",
    "Benjamin",
    "Bill",
    "Bobby",
    "Bryson",
    "Cameron",
    "Carter",
    "Casey",
    "Chad",
    "Charles",
    "Chris",
    "Christian",
    "Christopher",
    "Cole",
    "Colin",
    "Connor",
    "Cody",
    "Craig",
    "Damon",
    "Daniel",
    "Darren",
    "David",
    "Dennis",
    "Derek",
    "Devin",
    "Dylan",
    "Drew",
    "Edward",
    "Elliott",
    "Erik",
    "Ethan",
    "Evan",
    "Felix",
    "Finn",
    "Francis",
    "Frank",
    "Gabriel",
    "Garrett",
    "Gavin",
    "George",
    "Grant",
    "Greg",
    "Gregory",
    "Hal",
    "Hank",
    "Harrison",
    "Hayden",
    "Henry",
    "Hunter",
    "Ian",
    "Isaac",
    "Jack",
    "Jackson",
    "Jacob",
    "James",
    "Jason",
    "Jay",
    "Jeff",
    "Jeremy",
    "Jesse",
    "Joel",
    "John",
    "Jonathan",
    "Jordan",
    "Joseph",
    "Joshua",
    "Justin",
    "Kai",
    "Karl",
    "Kevin",
    "Kyle",
    "Lars",
    "Leo",
    "Liam",
    "Logan",
    "Luke",
    "Mark",
    "Martin",
    "Mason",
    "Matthew",
    "Max",
    "Michael",
    "Mike",
    "Mitchell",
    "Nathan",
    "Neil",
    "Nicholas",
    "Nick",
    "Noah",
    "Oliver",
    "Oscar",
    "Owen",
    "Patrick",
    "Paul",
    "Peter",
    "Philip",
    "Quinn",
    "Rafael",
    "Raymond",
    "Reid",
    "Richard",
    "Riley",
    "Robert",
    "Ryan",
    "Sam",
    "Samuel",
    "Scott",
    "Sean",
    "Sergey",
    "Seth",
    "Shane",
    "Shaun",
    "Simon",
    "Spencer",
    "Stefan",
    "Stephen",
    "Steve",
    "Steven",
    "Tanner",
    "Taylor",
    "Theo",
    "Thomas",
    "Tim",
    "Timothy",
    "Toby",
    "Todd",
    "Travis",
    "Trevor",
    "Tyler",
    "Victor",
    "Vincent",
    "Wade",
    "Warren",
    "Wayne",
    "William",
    "Wyatt",
    "Xavier",
    "Zach",
    "Zachary",
    "Zane",
    "Antonin",
    "Bohdan",
    "Dalibor",
    "Dominik",
    "Emil",
    "Filip",
    "Jan",
    "Jiri",
    "Lukas",
    "Marek",
    "Martin",
    "Michal",
    "Pavel",
    "Radek",
    "Roman",
    "Tomas",
    "Vojtech",
    "Yuri",
    "Maxim",
    "Kirill",
    "Dmitri",
    "Ilya",
    "Nikita",
    "Sergei",
    "Aleksei",
    "Andrei",
    "Rasmus",
    "Saku",
    "Teemu",
]

LNAME = [
    "Anderson",
    "Berg",
    "Carlsson",
    "Davis",
    "Eriksson",
    "Forsberg",
    "Gagnon",
    "Hansen",
    "Ivanov",
    "Johansson",
    "Karlsson",
    "Larsson",
    "Mäkinen",
    "Niemi",
    "Olofsson",
    "Peterson",
    "Quinn",
    "Rasmussen",
    "Svensson",
    "Tkachuk",
    "Ulmanen",
    "Vasilev",
    "Wagner",
    "Xuereb",
    "Young",
    "Zajac",
    "Arvidsson",
    "Boucher",
    "Carter",
    "Duchene",
    "Eklund",
    "Fischer",
    "Granlund",
    "Hughes",
    "Ibrahim",
    "Jensen",
    "Kozlov",
    "Lindberg",
    "Miller",
    "Nylander",
    "Olsen",
    "Pietrangelo",
    "Rossi",
    "Stålberg",
    "Tremblay",
    "Undström",
    "Väisänen",
    "White",
    "Zubov",
    "Bäckström",
    "Björk",
    "Clarke",
    "Durand",
    "Ekholm",
    "Fournier",
    "Gruber",
    "Håkansson",
    "Inoue",
    "Järvinen",
    "Kämpf",
    "Lavoie",
    "Morrison",
    "Nordström",
    "Ouellet",
    "Pavlov",
    "Renaud",
    "Sandström",
    "Trudeau",
    "Vatanen",
    "Wasilewski",
    "Åström",
    "Béliveau",
    "Côté",
    "Dahl",
    "Engström",
    "Falk",
    "Gauthier",
    "Heikkinen",
    "Isaksson",
    "Jakobsson",
    "Koponen",
    "Laurent",
    "Magnusson",
    "Nelson",
    "Orr",
    "Perron",
    "Rydberg",
    "Strom",
    "Turcotte",
    "Uotila",
    "Välimäki",
    "Wright",
    "Zachary",
    "Beauchamp",
    "Cloutier",
    "Deveau",
    "Fleury",
    "Gagné",
    "Häkkinen",
    "Ignatiev",
    "Jokinen",
    "Koskinen",
    "Lundqvist",
    "Mathieu",
    "Nilsson",
    "Oja",
    "Pihlaja",
    "Saarinen",
    "Tervo",
    "Ullman",
    "Vézina",
    "Ward",
    "Zinchenko",
    "Asplund",
    "Bélanger",
    "Creel",
    "Dufour",
    "Elias",
    "Favreau",
    "Geller",
    "Hansson",
    "Isherwood",
    "Jorgensen",
    "Keller",
    "Lefebvre",
    "Monahan",
    "Nordahl",
    "Olsson",
    "Peters",
    "Sihvonen",
    "Thompson",
    "Uhre",
    "Vesterinen",
    "Watkins",
    "Zetterberg",
    "Barkov",
    "Cournoyer",
    "DeAngelo",
    "Eason",
    "Fletcher",
    "Gustavsson",
    "Heller",
    "Isakov",
    "Jokela",
    "Karlsson",
    "Lindholm",
    "Mairesse",
    "Nyström",
    "Ojala",
    "Pekka",
    "Stenlund",
    "Timonen",
    "Utter",
    "Valimaki",
    "Wilkins",
    "Zou",
    "Blais",
    "Charbonneau",
    "Decker",
    "Eliasson",
    "Fiske",
    "Gårdh",
    "Hedman",
    "Isak",
    "Jensen",
    "Kallio",
    "Lund",
    "Mäkelä",
    "Nordquist",
    "Oberg",
    "Pohl",
    "Rosen",
    "Ström",
    "Tanner",
    "Ulrich",
    "Vainio",
    "Wennerström",
    "Zuniga",
    "Axelsson",
    "Bergman",
    "Connolly",
    "Daly",
    "Estrada",
    "Francis",
    "Gibson",
    "Häyrynen",
    "Ito",
    "Koskela",
    "Lundberg",
    "Manninen",
    "Norrman",
    "Persson",
    "Ruutu",
    "Soderberg",
    "Tamm",
    "Uusitalo",
    "Vänskä",
    "Wallin",
    "Bergqvist",
    "Crane",
    "Ducharme",
    "Eklöf",
    "Forsetlund",
    "Gillespie",
    "Holm",
    "Ivarsson",
    "Jansson",
    "Korpela",
    "Lind",
    "Mårtensson",
    "Nyqvist",
    "Olafsson",
    "Proulx",
    "Roy",
    "Salo",
    "Tervonen",
    "Vasko",
    "Wiberg",
    "Zetterqvist",
    "Aalto",
    "Borg",
    "Cecchini",
    "Degen",
    "Ek",
    "Franz",
    "Gustafson",
    "Härkönen",
    "Isenberg",
    "Kvist",
    "Lindström",
    "Möller",
    "Nystrom",
    "Oliveira",
    "Pekkarinen",
    "Rantanen",
    "Thörn",
    "Vesala",
    "Westerlund",
    "Ziegler",
    "Ahlberg",
    "Bäck",
    "Dreyer",
]


def print_affiliation():
    print("")
    for i, f in enumerate(AFFILIATION):
        print(
            i + 1,
            f["NHL"],
            "<->",
            f["AHL"],
            "<->",
            f["EU"],
            "<->",
            f["CHL"],
            "<->",
            f["SPHL"],
            "<->",
            f["FHL"],
            "<->",
            f["REC1"],
            "<->",
            f["REC2"],
        )


FRANCHISE_COUNT = len(teamnames)


class Franchise:
    def __init__(
        self,
        nhl_team,
        ahl_team,
        eu_team,
        chl_team,
        sphl_team,
        fhl_team,
        rec1_team,
        rec2_team,
    ):
        self.nhl = nhl_team
        self.ahl = ahl_team
        self.eu = eu_team
        self.chl = chl_team
        self.sphl = sphl_team
        self.fhl = fhl_team
        self.rec1 = rec1_team
        self.rec2 = rec2_team

        self.all_teams = [
            self.nhl,
            self.ahl,
            self.eu,
            self.chl,
            self.sphl,
            self.fhl,
            self.rec1,
            self.rec2,
        ]


AFFILIATION = [
    {
        "NHL": teamnames[i],
        "AHL": AHLteamnames[i],
        "EU": EUteamnames[i],
        "CHL": CHLteamnames[i],
        "SPHL": SPHLteamnames[i],
        "FHL": FHLteamnames[i],
        "REC1": REC1teamnames[i],
        "REC2": REC2teamnames[i],
    }
    for i in range(len(teamnames))
]

if __name__ == "__main__":
    for i, f in enumerate(AFFILIATION):
        print(
            i + 1,
            f["NHL"],
            "<->",
            f["AHL"],
            "<->",
            f["EU"],
            "<->",
            f["CHL"],
            "<->",
            f["SPHL"],
            "<->",
            f["FHL"],
            "<->",
            f["REC1"],
            "<->",
            f["REC2"],
        )
